import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

import ToastProvider from "@/providers/toast-providers";

// styles
import "./globals.css";

// components
import HeaderNav from "@/components/layouts/header-nav";
import CartAction from "@/components/layouts/cart-action";

// clerk 認証機能
import { ClerkProvider } from "@clerk/nextjs";
import { jaJP } from "@clerk/localizations"; // 日本言語を取得

const inter = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={jaJP}>
      <html lang="ja">
        <body className={inter.className}>
          <HeaderNav />
          {children}
          <CartAction />
          <ToastProvider />
        </body>
      </html>
    </ClerkProvider>
  );
}
